# name: Build and Deploy to Elastic Beanstalk

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up JDK 11
#       uses: actions/setup-java@v4
#       with:
#         distribution: 'adopt'
#         java-version: '11'

#     - name: Build with Maven
#       run: mvn clean package

#     - name: Archive Artifact
#       uses: actions/upload-artifact@v4
#       with:
#         name: my-app
#         path: target/*.jar

#   publish:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Download Artifact
#       uses: actions/download-artifact@v4
#       with:
#         name: my-app
#         path: ./target

#     - name: Publish to GitHub Packages
#       run: mvn deploy -B
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         GITHUB_ACTOR: ${{ github.actor }}

#   deploy:
#     runs-on: ubuntu-latest
#     needs: publish

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Download Artifact
#       uses: actions/download-artifact@v4
#       with:
#         name: my-app
#         path: ./target

#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_REGION }}

#     - name: Deploy to Elastic Beanstalk
#       env:
#         EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
#         EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
#         EB_BUCKET: ${{ secrets.EB_BUCKET }}
#       run: |
#         mkdir deploy
#         cp target/*.jar deploy/
#         cd deploy
#         zip -r deploy.zip .
#         aws s3 cp deploy.zip s3://$EB_BUCKET/deploy.zip
#         aws elasticbeanstalk create-application-version --application-name $EB_APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=$EB_BUCKET,S3Key=deploy.zip
#         aws elasticbeanstalk update-environment --environment-name $EB_ENVIRONMENT_NAME --version-label $GITHUB_SHA
