name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        working-directory: ./terraform_setup_for_elastic_beanstalk_maven_deployment
        run: terraform init -input=false
          
      - name: Terraform Validate
        working-directory: ./terraform_setup_for_elastic_beanstalk_maven_deployment
        run: terraform validate

      - name: Terraform Destroy
        working-directory: ./terraform_setup_for_elastic_beanstalk_maven_deployment
        run: terraform destroy -auto-approve
