# name: Terraform Destroy

# on:
#   workflow_dispatch:

# jobs:
#   terraform_destroy:
#     runs-on: ubuntu-latest
#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: CD to terraform folder
#         run: cd terraform_setup_for_elastic_beanstalk_maven_deployment/

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: "1.1.7"

#       - name: Terraform Init
#         run: terraform init -input=false
          
#       - name: Terraform Validate
#         run: terraform validate

#       - name: Terraform Destroy
#         run: terraform destroy -auto-approve
